Import('*')

# Define all source files that will be part of the cleaning process
r_sources = [
    '#source/derived/candidates_clean/00_candidates_main.R',
    '#source/derived/candidates_clean/01_candidates_imports.R',
    '#source/derived/candidates_clean/02_candidates_helper_functions.R',
    '#source/derived/candidates_clean/03_candidates_clean_n1.R'
]

# Define main target and source
target = ['#output/derived/candidates_clean/candidates_clean_n1.csv']
source = ['#source/derived/candidates_clean/00_candidates_main.R']

# Add dependencies for all R scripts and raw data
env.Depends(target, r_sources)
env.Depends(target, '#source/raw_data/candidates.csv')

# Build command
env.R(target, source)