Import('*')

# target = ['#output/derived/wb_clean/gdp_education.csv']
# source = ['#source/derived/wb_clean/build.py',
#           '#datastore/raw/world_bank/orig/API_NY.GDP.PCAP.CD_DS2_en_csv_v2_1740213.csv',
#           '#datastore/raw/world_bank/orig/API_SE.XPD.TOTL.GD.ZS_DS2_en_csv_v2_1740282.csv']
# env.Python(target, source)

# target = ['#output/derived/wb_clean/gdp_education_logs.csv']
# source = ['#source/derived/wb_clean/takelogs.do',
#           '#output/derived/wb_clean/gdp_education.csv']
# env.Stata(target, source)

target = ['#output/derived/candidates_clean/candidates_clean_n1.csv']
source = ['#source/derived/candidates_clean/00_candidates_main.R']
env.Depends(target, '#source/raw_data/candidates.csv')
env.R(target, source)